name: .Net

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: "mbti_db"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "1234"
          #POSTGRES_HOST: postgres
        ports:
          - 5432:5432
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
              
    - name: Install dependencies
      run: dotnet restore
      working-directory: mbti_web
      
    - name: Build
      run: dotnet build
      working-directory: mbti_web
      
    - name: Restore dependencies UnitTest
      run: dotnet restore
      working-directory: UnitTest
    - name: Build UnitTest
      run: dotnet build --no-restore                 
      working-directory: UnitTest
    - name: UnitTest
      run: dotnet test UnitTests
      
    - name: Restore dependencies IntegrationTests
      run: dotnet restore
      working-directory: IntegrationTests
    - name: Build IntegrationTests
      run: dotnet build --no-restore                 
      working-directory: IntegrationTests
    - name: IntegrationTests
      run: dotnet test IntegrationTests

    - name: Restore dependencies E2ETest
      run: dotnet restore
      working-directory: E2ETest
    - name: Build E2ETest
      run: dotnet build --no-restore                 
      working-directory: E2ETest
    - name: E2ETest
      run: dotnet test E2ETest
      
    
