name: .Net

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies UnitTests
      run: dotnet restore
      working-directory: UnitTests
    
    - name: Build UnitTests
      run: dotnet build --no-restore
      working-directory: UnitTests
      
    - name: Unit Tests
      run: dotnet test UnitTests
      working-directory: UnitTests
    
    
