name: .Net

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: "mbti_db"
          SCHEMA: "MBTI"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "1234"
        ports:
          - 5432:5432
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
              
    - name: Install dependencies
      run: dotnet restore
      working-directory: mbti_web
      
    - name: Build
      run: dotnet build
      working-directory: mbti_web
      
      
    #- name: UnitTest
    #  run: dotnet test UnitTests

    - name: E2ETest
      run: dotnet test E2ETest
      
    
